// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://podevents.app/terms",
        "contact": {
            "name": "API Support",
            "email": "support@podevents.app"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/exchange": {
            "post": {
                "description": "Exchanges the temporary auth code (obtained from the frontend callback redirect) for a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Exchange auth code for JWT",
                "parameters": [
                    {
                        "description": "Auth exchange request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthExchangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Authentication completed",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "400": {
                        "description": "missing auth exchange code",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "401": {
                        "description": "invalid or expired auth exchange code",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the authenticated user's profile",
                "tags": [
                    "Auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "User fetched successfully",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/auth/spotify/callback": {
            "get": {
                "description": "Handles the redirect from Spotify after user authorization, exchanges code for tokens, and redirects to frontend with an exchange code",
                "tags": [
                    "Auth"
                ],
                "summary": "Spotify OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from Spotify",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth state token for CSRF protection",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    }
                }
            }
        },
        "/auth/spotify/login": {
            "get": {
                "description": "Generates an OAuth state token and redirects to Spotify's authorization page",
                "tags": [
                    "Auth"
                ],
                "summary": "Initiate Spotify OAuth login",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    }
                }
            }
        },
        "/channels": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all notification channels for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "List notification channels",
                "responses": {
                    "200": {
                        "description": "Channels fetched",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new notification channel for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Create notification channel",
                "parameters": [
                    {
                        "description": "Channel details",
                        "name": "channel",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateChannelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Channel created",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "422": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/channels/{channelID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a notification channel by its UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Delete notification channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel UUID",
                        "name": "channelID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Channel deleted",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Channel not found",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/channels/{channelID}/toggle": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Enable or disable a notification channel by its UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channels"
                ],
                "summary": "Toggle notification channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel UUID",
                        "name": "channelID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Toggle active status",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ToggleActiveChannelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Channel status updated",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Channel not found",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the dashboard overview with setup progress and statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get dashboard summary",
                "responses": {
                    "200": {
                        "description": "dashboard summary fetched successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.DashboardSummaryDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "failed to get dashboard summary",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the database is reachable",
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "unhealthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/shows/saved": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the current user's saved/podcasts from Spotify",
                "tags": [
                    "Shows"
                ],
                "summary": "Get saved shows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query to filter saved shows",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "show fetched successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.SavedShowResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/shows/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Search for podcast shows on Spotify",
                "tags": [
                    "Shows"
                ],
                "summary": "Search shows",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum results (default 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Result offset (default 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "show fetched successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.SavedShowResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid parameters",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/shows/{spotifyShowId}/subscribe": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Subscribe the current user to a podcast show by Spotify show ID",
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Subscribe to a show",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Spotify show ID (22 characters)",
                        "name": "spotifyShowId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "subscribed successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.SubscriptionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid spotify show ID",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "404": {
                        "description": "podcast show not found",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "409": {
                        "description": "already subscribed",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all of the current user's active subscriptions",
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Get subscriptions",
                "responses": {
                    "200": {
                        "description": "subscriptions fetched successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.SubscriptionResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a subscription by its UUID",
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Unsubscribe from a show",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "unsubscribed successfully",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "400": {
                        "description": "invalid subscription ID",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "404": {
                        "description": "subscription not found",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/telegram/generate-link": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generate a one-time link to connect a Telegram chat to the user's PodEvents account",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telegram"
                ],
                "summary": "Generate Telegram connect link",
                "responses": {
                    "200": {
                        "description": "Telegram connect link created",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "409": {
                        "description": "already have a Telegram channel",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/webhooks/telegram": {
            "post": {
                "description": "Handle incoming updates from Telegram (bot commands, messages)",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Telegram"
                ],
                "summary": "Telegram webhook",
                "parameters": [
                    {
                        "description": "Telegram update",
                        "name": "update",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/telegram.Update"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "invalid telegram secret"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuthExchangeRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "abc123"
                }
            }
        },
        "dto.CreateChannelRequest": {
            "type": "object",
            "required": [
                "channel_type",
                "destination"
            ],
            "properties": {
                "channel_type": {
                    "description": "Channel type: slack_webhook, discord_webhook, whatsapp, or telegram",
                    "enum": [
                        "slack_webhook",
                        "discord_webhook",
                        "whatsapp",
                        "telegram"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.ChannelType"
                        }
                    ],
                    "example": "slack_webhook"
                },
                "destination": {
                    "description": "Destination URL or identifier for the channel",
                    "type": "string",
                    "example": "https://hooks.slack.com/services/..."
                },
                "label": {
                    "description": "Optional label to identify the channel",
                    "type": "string",
                    "example": "Work Slack"
                }
            }
        },
        "dto.DashboardItems": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "dto.DashboardSetupResponse": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DashboardItems"
                    }
                },
                "percent": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dto.DashboardStatsResponse": {
            "type": "object",
            "properties": {
                "active_channels": {
                    "type": "integer"
                },
                "new_episodes_this_week": {
                    "type": "integer"
                },
                "notification_sent": {
                    "type": "integer"
                },
                "podcasts_tracked": {
                    "type": "integer"
                }
            }
        },
        "dto.DashboardSummaryDTO": {
            "type": "object",
            "properties": {
                "setup": {
                    "$ref": "#/definitions/dto.DashboardSetupResponse"
                },
                "stats": {
                    "$ref": "#/definitions/dto.DashboardStatsResponse"
                }
            }
        },
        "dto.PodcastShowResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "latest_episode_id": {
                    "type": "string"
                },
                "latest_episode_published_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "spotify_show_id": {
                    "type": "string"
                },
                "spotify_url": {
                    "type": "string"
                }
            }
        },
        "dto.SavedShowResponse": {
            "type": "object",
            "properties": {
                "added_at": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Joe Rogan's podcast"
                },
                "id": {
                    "type": "string",
                    "example": "4GvhKq1eEYj7JzAKUwWmNc"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://i.scdn.co/image/abc123"
                },
                "name": {
                    "type": "string",
                    "example": "The Joe Rogan Experience"
                },
                "spotify_url": {
                    "type": "string",
                    "example": "https://open.spotify.com/show/abc123"
                },
                "total_episodes": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "dto.SubscriptionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "podcast_show": {
                    "$ref": "#/definitions/dto.PodcastShowResponse"
                },
                "podcast_show_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.ToggleActiveChannelRequest": {
            "type": "object",
            "required": [
                "is_active"
            ],
            "properties": {
                "is_active": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.ChannelType": {
            "type": "string",
            "enum": [
                "slack_webhook",
                "discord_webhook",
                "telegram",
                "whatsapp"
            ],
            "x-enum-varnames": [
                "ChannelTypeSlack",
                "ChannelTypeDiscord",
                "ChannelTypeTelegram",
                "ChannelTypeWhatsApp"
            ]
        },
        "response.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/response.ErrorInfo"
                },
                "message": {
                    "type": "string"
                },
                "meta": {
                    "$ref": "#/definitions/response.PaginationMeta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "response.ErrorInfo": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "response.PaginationMeta": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "telegram.Chat": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "telegram.Message": {
            "type": "object",
            "properties": {
                "chat": {
                    "$ref": "#/definitions/telegram.Chat"
                },
                "from": {
                    "$ref": "#/definitions/telegram.User"
                },
                "message_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "telegram.Update": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/telegram.Message"
                },
                "update_id": {
                    "type": "integer"
                }
            }
        },
        "telegram.User": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "PodEvents API",
	Description:      "API for PodEvents - podcast notification platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
